/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package monolith.pg.runtime;

import java.util.Set;
import java.util.function.Function;

/**
 * A query's reactive-invalidation rule, generated by the processor from a {@code @PgQuery}'s
 * parsed tables, join keys, and param. Given a changed table and a way to read the changed
 * row's column values, it returns the param values whose live-query buckets must be woken.
 *
 * <p>For the table that carries the param column this is a direct read; for a joined table it
 * is the codegen-derived back-reference (a lookup along the join path), the join back-reference
 * reduced to generated SQL, which is what the <i>declared</i> {@code @PgQuery} model makes possible.
 */
public interface PgInvalidationRule {

  /** The query name (the subscription bucket key). */
  String query();

  /** The tables this query reads (for registration / coarse fallback). */
  String[] tables();

  /**
   * The param values affected by a change.
   *
   * @param changedTable the table the WAL change touched
   * @param valuesOf     column name → all of that column's values in the change (old + new under
   *                     REPLICA IDENTITY FULL)
   * @param pool         used for the join back-reference lookups
   */
  Set<String> affectedParams(String changedTable, Function<String, Set<String>> valuesOf, PgPool pool);
}
